### ISSUE TITLE
provide guidelines to install from source

### ISSUE THREAD

**Issue by toni-moreno** [changkun/occamy#23]
**Describe the bug**

Hi I'm new and would like doing some code investigation to see if could be good for my project with a few additions, but  I can not install  from github sources .

After install libcairo2 and libguac under ubuntu 18.04 this error happens.

```bash
vant@vant-N2x0WU:~/go/src/github.com$ go get github.com/changkun/occamy
# github.com/changkun/occamy/lib
/tmp/go-build751212863/b135/_x002.o: En la función `_cgo_84b46eb4f0ae_Cfunc_guac_client_load_plugin':
/tmp/go-build/cgo-gcc-prolog:96: referencia a `guac_client_load_plugin' sin definir
/tmp/go-build751212863/b135/_x005.o: En la función `_cgo_84b46eb4f0ae_Cfunc_guac_user_alloc':
/tmp/go-build/cgo-gcc-prolog:147: referencia a `guac_user_alloc' sin definir
/tmp/go-build751212863/b135/_x005.o: En la función `_cgo_84b46eb4f0ae_Cfunc_guac_client_add_user':
/tmp/go-build/cgo-gcc-prolog:82: referencia a `guac_client_add_user' sin definir
/tmp/go-build751212863/b135/_x005.o: En la función `_cgo_84b46eb4f0ae_Cfunc_guac_client_remove_user':
/tmp/go-build/cgo-gcc-prolog:95: referencia a `guac_client_remove_user' sin definir
/tmp/go-build751212863/b135/_x005.o: En la función `_cgo_84b46eb4f0ae_Cfunc_guac_user_free':
/tmp/go-build/cgo-gcc-prolog:162: referencia a `guac_user_free' sin definir
/tmp/go-build751212863/b135/_x005.o: En la función `_cgo_84b46eb4f0ae_Cfunc_guac_user_input_thread':
/tmp/go-build/cgo-gcc-prolog:176: referencia a `guac_user_input_thread' sin definir
collect2: error: ld returned 1 exit status
```
**To Reproduce**

```
 sudo apt-get install libcairo2-dev
 sudo apt-get install libguac-dev
 go get github.com/changkun/occamy
```

**Expected behavior**

download code without errors

**Desktop (please complete the following information):**
 - OS: `Linux 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by changkun** [comment]
Hi, we do not support install by `go get` at the moment.

It is recommended to use docker by using `make build`

**Comment by toni-moreno** [comment]
Hi @changkun 
We indeed would like investigate a little the code so I need compile and test outside docker. Could be interesting if we could contribute to add new features.

**Comment by changkun** [comment]
@toni-moreno Hi, thank you so much for your interest. 

In the Dockerfile, you can find the instructions to install the occamy project natively.

**Comment by toni-moreno** [comment]
Hi @changkun I will review in a few days
