### ISSUE TITLE
rdp 代理

### ISSUE THREAD

**Issue by laixiaohuai** [changkun/occamy#24]
大佬可以写个rdp 代理demo 嘛，通过freeRDP或windows本身远程桌面工具直接连接这个代理，就可以直接连到目标机器

**Comment by changkun** [comment]
你好，我没太看懂你的想法？occamy 的目的是消除 vnc/rdp/ssh 之间的差异，作为中间 proxy 使用，如果 freeRDP 和 windows remote desktop client 直接链接 rdp proxy 为什么不直接连接 rdp server？这时 rdp proxy 与普通的 proxy （例如 nginx）的区别是什么？

**Comment by laixiaohuai** [comment]
最近正好&nbsp;在写堡垒机。
ssh&nbsp;正好&nbsp;搞定了，但是rdp这块还没头绪，你的代码里有c，我只懂go和python和vue



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ou Changkun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月27日(星期一) 中午11:15
收件人:&nbsp;"changkun/occamy"<occamy@noreply.github.com&gt;;
抄送:&nbsp;"博恩"<429472406@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [changkun/occamy] rdp 代理 (#24)




你好，我没太看懂你的想法？occamy 的目的是消除 vnc/rdp/ssh 之间的差异，作为中间 proxy 使用，如果 freeRDP 和 windows remote desktop client 直接链接 rdp proxy 为什么不直接连接 rdp server？这时 rdp proxy 与普通的 proxy （例如 nginx）的区别是什么？

**Comment by changkun** [comment]
根据你的描述，似乎并不符合此项目的宗旨，暂时关闭。如果有异议，可以重新打开此 issue 进一步讨论。
