### ISSUE TITLE
404 error on /api/v1/login

### ISSUE THREAD

**Issue by denis-b** [changkun/occamy#26]
Hello,
I tried to run occamy with real rdp server : 
- compiled docker, 
- changed conf.yaml to 
address: 192.168.201.12:5636 (my test machine)
- run docker with docker run --network="host" -itd occamy:latest /occamy/occamyd -conf=./conf.yaml
- access to windows machine: http://192.168.201.12:5636/static is ok, I can connect to remote windows machine.

- modify sources in client/occamy-web to replace 0.0.0.0:5636 with 192.168.201.12:5636 
- npm install && npm run build
- copy dist/ to my webserver,
- connect to http://webserver/dist
- login page is ok, but error 404 when connecting. 

Did I missed something ?

curl http://192.168.201.12:5636/api/v1/connect
{"code":401,"message":"cookie token is empty"}

curl http://192.168.201.12:5636/api/v1/login
404 page not found

**Comment by changkun** [comment]
Thanks for reporting the issue.

I think you didn't enable the client. Occamy doesn't offer `/api/v1/login` by default.
Because in common practice, a JWT token should not be issued by the service itself.

If you would like to test Occamy, modify `conf.yaml` and enable the web client.

**Comment by changkun** [comment]
Timeout, close. Feel free to reopen it again.
