### ISSUE TITLE
Fail to build docker

### ISSUE THREAD

**Issue by dyaskur** [changkun/occamy#44]
**To Reproduce**
```
git clone https://github.com/changkun/occamy.git
cd occamy
make build
```
then return
```
docker build -t occamy:0.4.0-25-gd220486 -t occamy:latest -f docker/Dockerfile .
make: docker: No such file or directory
make: *** [build] Error
```

**Desktop (please complete the following information):**
 - OS: MacOS big sur

**Comment by mhjor70** [comment]
Double check the got download had a dockerfile and it’s the proper case

-——•
Michele (Mike) Hjorleifsson
772-224-8913 x4
***@***.***
________________________________
From: Muhammad Dyas Yaskur ***@***.***>
Sent: Tuesday, July 6, 2021 7:03:35 PM
To: changkun/occamy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [changkun/occamy] Fail to build docker (#44)


To Reproduce
Steps to reproduce the behavior:

git clone https://github.com/changkun/occamy.git
cd occamy
make build


then return

docker build -t occamy:0.4.0-25-gd220486 -t occamy:latest -f docker/Dockerfile .
make: docker: No such file or directory
make: *** [build] Error


Desktop (please complete the following information):

  *   OS: MacOS big sur

**Comment by dyaskur** [comment]
oh yes, sorry, I removed docker from my computer, but after I install docked, it;s return:

```
docker build -t occamy:0.4.0-25-gd220486 -t occamy:latest -f docker/Dockerfile .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make: *** [build] Error 1
```

**Comment by mhjor70** [comment]
There should be an icon in your menu bar at the top right that looks like a little whale click it and select start docker
If it’s not there reboot it should appear

-——•
Michele (Mike) Hjorleifsson
772-224-8913 x4
***@***.***
________________________________

**Comment by changkun** [comment]
```
docker build -t occamy:0.4.0-25-gd220486 -t occamy:latest -f docker/Dockerfile .
make: docker: No such file or directory
make: *** [build] Error
```

This looks like you are not in the correct folder.

```
docker build -t occamy:0.4.0-25-gd220486 -t occamy:latest -f docker/Dockerfile .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make: *** [build] Error 1
```

This looks like you don't have docker running.

**Comment by changkun** [comment]
Close due to no response.

**Comment by dyaskur** [comment]
sorry for late response, but yes, its no docker running. after run it worked. thanks
